version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">=11"
      - dependency-name: "husky"
        versions:
          - ">=5"
    open-pull-requests-limit: 15
