version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        versions:
          - "> 10"
      - dependency-name: "husky"
        versions:
          - "> 4"
    open-pull-requests-limit: 15
