version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: daily
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">=11"
      - dependency-name: "husky"
        versions:
          - ">=5"
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: daily
