name: ci

on:
  push:
    branches: [master, next, beta, alpha]
  pull_request:
    branches: [master, next, beta, alpha]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [10, 12, 14]

    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  release:
    runs-on: ubuntu-latest

    # Prevent run if coming from forks
    if: github.event.pull_request.head.repo.full_name == github.repository

    needs: test

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
      - uses: volta-cli/action@v1
      - run: npm ci
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
